# Rosie Pattern Language
os:
  - linux
  - osx

branches:
  only:
  - master
  
before_install:

language: C
compiler: gcc

install: make
script: make test

language: python
python:
  - "2.7"

install: pip install --user cffi

