# Rosie Pattern Language
os:
  - linux
#  - osx

# osx_image:
#   - xcode7.3
#   - xcode8
#   - xcode8.1

branches:
  only:
  - master
  - preview
  
before_install:

language: C
compiler: gcc

install: make
script: make test


